name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Verilog tools
        run: |
          sudo apt-get install -y iverilog gtkwave

      - name: Run Simulation
        run: |
          iverilog -o sim src/tb.v src/fir.v
          vvp sim

      - name: Save Waveform
        run: |
          mv tb.vcd simulation_results.vcd
        artifacts:
          paths:
            - simulation_results.vcd
